name: Build and Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear docker context
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop next-app
            docker system prune -a -f  

      - name: Send files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "./"
          target: "/app"

      - name: Build and Run Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /${{ secrets.SERVER_USERNAME }}/app
            docker build -t next-app:latest .
            docker run -d \
              --name=next-app \
              -e CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} \
              -e CLIENT_ID=${{ secrets.CLIENT_ID }} \
              -p 3000:3000 \
              next-app:latest